# Generated by Django 4.1.1 on 2023-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
