# Generated by Django 4.1.1 on 2023-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
